name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ['x86_64', 'aarch64']
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.arch }} osxcross image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/pschichtel/osxcross/${{ matrix.arch }}:${{ github.ref_name }}
          build-args: |
            CROSS_TRIPLE=${{ matrix.arch }}-apple-darwin
          cache-from: type=gha
          cache-to: type=gha,mode=max

