name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-osx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate container tag
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "container_tag=${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Dockerfile.osx
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/pschichtel/cross-build/osx/:${{ steps.tag.outputs.container_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate container tag
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "container_tag=${DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Dockerfile.android
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/pschichtel/cross-build/android:${{ steps.tag.outputs.container_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

